class_name ForgeSectionGuides
extends RefCounted
## Single source of truth for the in-Forge step-by-step help. Add or update a
## page here whenever its workflow changes.

const GUIDES := {
	"Forge Home": [
		"Start here when you are unsure what to open. Forge changes how an asset looks; it does not change recipes, inventory rules, machine logic or saved-world identity.",
		"Open Asset Browser to edit an existing presentation, or New Asset Wizard to create the first Forge source for a gameplay ID.",
		"Look at the four totals: indexed presentations are all known assets, approved sources are live Forge replacements, drafts are work in progress, and legacy fallbacks still use older visuals.",
		"After opening an asset, use Block Surface for a cube made from six textures, Voxel Model for a sculpted 3D shape, or Compound & Sockets for machines with separate moving parts.",
		"Watch Live Preview while editing. Drag to orbit, Shift-drag or right/middle-drag to pan, scroll to zoom, and press Reset if the model leaves the frame.",
		"Press Save Draft regularly or Ctrl+S. Draft saves are recoverable and do not replace the approved in-game presentation.",
		"Press Validate or Ctrl+Enter before baking. Fix red errors first; read warnings to decide whether the result is intentional.",
		"Use Bake Preview for a temporary test. Use Approve & Bake only when the source is saved, validation has no blockers, and the model looks correct in preview and world tests.",
	],
	"Library & Create": [
		"Use this studio to find an existing stable gameplay identity before creating any visual source.",
		"Search Asset Browser when you know the name or ID; use New Asset Wizard when you need help selecting the authoring mode.",
		"Read Author and Inspect badges as capability labels. An Inspect route never claims it can rewrite its catalogue.",
		"Use Migration Register to understand legacy coverage without starting a bulk replacement or deleting fallbacks.",
		"Open the chosen record and confirm its stable ID in the context ribbon before moving to a specialist studio.",
	],
	"Items & Blocks": [
		"Open or create an asset first; asset-required workflows explain why they are disabled when nothing is open.",
		"Choose Surface for full cubes, Voxel Model for sculpted forms, and Compound for multiple named moving parts.",
		"Keep reusable palette roles and Material DNA canonical here. Other studios may reference them but do not duplicate them.",
		"Finish collision, icon, animation and variants before using World Test Preview.",
		"Switching studios preserves the open source, unsaved state, undo history and preview camera.",
	],
	"Structures & Buildings": [
		"Begin with Blueprint Catalogue to inspect definitions, modules, states and runtime products in the shared foundation index.",
		"Use Blueprint Handoff to follow canonical settlement blueprint IDs and their stable material or block references.",
		"Treat Inspect routes as read-only evidence views; they do not create a second blueprint registry.",
		"The composition editor is marked Planned until specialist editing, undo and validation contracts exist.",
		"Author referenced block presentations in Items & Blocks, then verify the assembled result through Test & Delivery.",
	],
	"Characters & Creatures": [
		"Use Entity Catalogue to inspect stable entity definitions, assembly profiles and gameplay proxy records.",
		"Use Body Plans & Rigs for anatomy, semantic rigs, retarget maps and animation-library coverage.",
		"Use Equipment & Variants for fitting and appearance records without treating the catalogue as a visual fitting editor.",
		"Animation remains owned by its entity or asset domain; shared event contracts belong in Test & Delivery.",
		"The Entity Model Editor remains Planned and disabled until its authoring contract is implemented.",
	],
	"VFX": [
		"The hub reports real VFX definitions, forms and graph records from the shared source index.",
		"Open Effects, Graphs & Forms to inspect bounds, families, voxel forms, LOD and budget contracts.",
		"Do not infer authoring support from a graph record: the Live VFX Graph Editor remains explicitly Planned.",
		"Use deterministic capture and dense-scene tests in Test & Delivery before requesting visual approval.",
		"Reduced-motion users receive static hub decoration and bounded preview equivalents.",
	],
	"Audio": [
		"The hub reports real Sound Events, sources and ambience plans and never autoplays audio.",
		"Open Sound Events & Sources to inspect provenance, seeded variation, concurrency, captions and spatial profiles.",
		"Do not infer waveform editing from the catalogue: the Waveform & Event Editor remains explicitly Planned.",
		"Run listening, accessibility, rights and multi-listener checks in Test & Delivery before publication.",
		"Keep stable ownership and stop paths visible for persistent or looping sounds.",
	],
	"Test & Delivery": [
		"Use this studio after specialist work to inspect shared presentation contracts, profiles and spatial roles.",
		"Run Accessibility Preview, deterministic Capture & Replay and the Test Laboratory before publication.",
		"Open Validation Centre for the current asset; blockers prevent approval while warnings require deliberate review.",
		"Stage and publish through Hot Reload only after complete dependency and compatibility validation.",
		"Approve & Bake stays in the fixed toolbar and keeps the source-hash rule: edited approved sources appear as draft until a matching approved product exists.",
	],
	"Asset Browser": [
		"Click the search box and type part of the visible name, stable gameplay ID, category or status. Clearing the box shows the complete catalogue again.",
		"A stable gameplay ID is the permanent identity used by recipes, saves and placement. Forge keeps that ID and supplies only a new visual presentation.",
		"Read the status at the end of each row: legacy_wrapper means no Forge source exists, draft means editable work exists, and approved means a baked Forge presentation is active.",
		"Click a row once to open it. If a Forge source already exists, Forge opens the relevant editor immediately.",
		"For a legacy presentation, review the displayed gameplay and presentation IDs, then click Create Project Source to make one linked draft without duplicating the gameplay item.",
		"If you need to choose Surface or Voxel before creation, use New Asset Wizard instead of the quick Create Project Source button.",
		"After opening, confirm the asset name in the left summary and the model in Live Preview before you begin painting.",
	],
	"New Asset Wizard": [
		"Open the Canonical gameplay presentation list and choose the existing block or item that should receive new visuals. This prevents duplicate gameplay IDs.",
		"Choose Recommended from the registry when you want Forge to select Surface, Voxel or Compound from the known shape and create starter geometry.",
		"Choose Block Surface when the finished asset is a full cube whose shape stays cubic and only its six painted faces need to change.",
		"Choose Voxel Model when you need a non-cube silhouette, holes, handles, blades, gears, cranks, furniture or any other sculpted 3D form. This option begins with a blank 32 x 32 x 32 volume.",
		"Click Create or Open Project Source. If the source already exists, Forge opens it and switches to the selected Surface or Voxel mode without deleting the inactive source.",
		"In the chosen editor, add at least one visible colour or voxel. A completely empty Voxel Model cannot validate or bake.",
		"Open Palette & Materials to name colours by purpose, choose exact colours, and bind each role to Material DNA.",
		"Open Collision & Placement and confirm how many world blocks the object occupies. Doors normally use Tall 1 x 2; ordinary blocks use Single 1 x 1.",
		"Save Draft, Validate, and then Bake Preview. Do not Approve & Bake until the preview, collision and placement footprint are all correct.",
	],
	"Block Surface Editor": [
		"Use Block Surface only for a cube. If you need to sculpt the silhouette, choose Voxel Model in Authoring mode and click Switch authoring mode; your surface work is kept for later.",
		"Choose Top, Bottom, North, South, East or West from Face. The canvas always edits only the selected face.",
		"Choose a Palette role. The colour square beside each name shows exactly what the selected role paints. Edit or add roles under Palette & Materials.",
		"Choose Pencil for single cells, Square/Circle/Diamond for larger stamps, or Fill bucket to replace one connected area. Shape radius controls how large the shape tools are.",
		"Hold the left mouse button and drag to keep painting. Hold the right mouse button and drag to restore the base role. Each continuous batch can be undone with Ctrl+Z.",
		"Enable Colour randomizer and tick the palette roles to mix while painting. Select at least two roles for visible variation such as stone speckle, wood grain or worn edges.",
		"To reuse a finished material layout, enter a Pattern name and click Save current face pattern. The pattern stores its colour roles and Material DNA, not only raw palette numbers.",
		"Select a saved pattern and click Apply pattern to current face. The pattern tiles across the face, so it can be reused on blocks of the same or different texture resolution.",
		"To duplicate a face, click Copy current face, tick every destination side, choose Copy, Mirror or Rotate, then click Paste to selected faces.",
		"Use Mirror current or Rotate current when only the selected face is upside down or facing the wrong direction. These actions do not replace the copied clipboard face.",
		"Enable 2 x 2 tile preview to inspect repeating seams. The tiled view is read-only; turn it off before painting again.",
		"Inspect all six sides in Live Preview, Save Draft, and Validate before baking. Pay special attention to top/bottom orientation and edge continuity.",
	],
	"Voxel Model Editor": [
		"Use Voxel Model for a true 3D shape. If the asset currently uses Block Surface, choose Voxel Model in Authoring mode and click Switch authoring mode; the previous surface source remains available.",
		"Think of the model as a stack of flat layers. Choose X to look from the side, Y to edit horizontal height layers, or Z to work from the front/back.",
		"Move the slice slider to the layer you want. The label shows the active axis and exact layer number; only that layer is painted.",
		"Choose a Palette role. Its colour swatch previews the paint colour. Add or change roles and Material DNA under Palette & Materials.",
		"Choose Pencil, Square, Circle, Diamond or Fill bucket, then choose Shape radius. Start with Pencil and radius 1 while learning.",
		"Hold left-click and drag to add or recolour microvoxels. Hold right-click and drag to remove them. Empty dark cells contain no geometry.",
		"Enable Mirror X for symmetrical objects. The gold centre line shows the mirror plane and every stroke is applied to both sides in one undoable command.",
		"Enable Colour randomizer and tick two or more palette roles to paint controlled colour variation across the model.",
		"Click Copy current layer, move the slider or change axis to a layer with matching dimensions, then click Paste onto current layer. Paste replaces occupied and empty cells and can be undone once.",
		"To reuse only a material layout, save the current layer as a named colour pattern. Applying that pattern recolours occupied voxels but keeps the destination object's shape and holes.",
		"Orbit Live Preview frequently and inspect the model from X, Y and Z. A good-looking front layer can still hide missing depth or accidental internal voxels.",
		"Save Draft and Validate. Resolve the empty-volume error, then use Bake Preview before approving the asset.",
	],
	"Palette Roles & Material DNA": [
		"A palette role is a named paint slot such as oak_base, oak_shadow, iron_edge or glow. Models store the role number so you can change the colour later without repainting every cell.",
		"Use the colour square and colour picker in each row to set the visible albedo colour. The small swatch updates immediately and Live Preview refreshes after the change.",
		"Rename generic roles to describe their purpose. Press Enter after typing the new role name so the change is applied.",
		"Open the Material DNA list on each row and choose the physical/rendering family that belongs to that colour. Existing material.generic.stone labels are shown as missing/custom until you choose a real library definition.",
		"Material DNA stores shared rendering intent such as wood, metal, glass, stone or emissive magic. It does not replace the visible palette colour.",
		"Click Add palette role when the asset needs another paint colour. New roles use an available library material instead of the old hard-coded generic stone reference.",
		"To make a new Material DNA, enter a lowercase Material ID beginning with material., a readable display name and a family such as wood or metal.",
		"Choose the rendering class, then set roughness, metallic and emission. Opaque is normal; transparent and emissive should be used only when the asset needs them.",
		"Click Create Material DNA. The new shared definition appears in the library and becomes available in every asset's material list.",
		"Return to Block Surface or Voxel Model, confirm the swatches and preview, then Save Draft and Validate material references.",
	],
	"Compound Parts & Sockets": [
		"Use Compound authoring for machines made from independently positioned or animated pieces, such as a furnace body, door, gear and flame.",
		"Review Named parts first. Each part key is a permanent animation target, so use simple stable names such as body, door, gear or flame.",
		"Enter a new part key and click Add voxel part. Open its voxel source through the available model workflow before relying on it in animation.",
		"Set the local transform to place the part relative to the asset origin. Keep the body near the origin so collision and placement remain predictable.",
		"Place a pivot at the real hinge or axle before animating. A door pivots at its edge; a gear pivots at its centre.",
		"Mark only genuinely moving pieces as animated. Static pieces can remain combined for a cheaper runtime mesh.",
		"Add typed sockets for flames, smoke, audio, held items, logistics or interactions, and parent them to the part they should follow.",
		"Validate against the presentation contract. Missing required parts or sockets are blockers because runtime effects and animations could not find their targets.",
	],
	"Collision & Placement Footprint": [
		"Collision controls where players and other bodies can physically move. Placement footprint reserves world-grid cells so two objects cannot occupy the same space.",
		"Start with the smallest simple collision boxes that cover the solid usable shape. Avoid filling intentional holes, doorways or handle gaps.",
		"Choose Single 1 x 1 for ordinary blocks, Tall 1 x 2 for full-height doors or other two-block objects, or author every occupied cell for an unusual shape.",
		"Confirm that the anchor cell is included in Occupied cells. The anchor is the origin used for placement and rotation.",
		"Set allowed rotations to match how the object may face in the world. Test all enabled rotations because a multi-cell footprint rotates with the asset.",
		"Choose allowed placement faces such as floor, wall or ceiling and set support requirements so objects cannot float accidentally.",
		"Use clearance cells for space that must stay empty while the object operates, such as the swing area in front of a door or machine access panel.",
		"Validate, then inspect one and several instances in World Test Preview to catch overlaps that a single model view cannot show.",
	],
	"Item, Held, Drop & Icon Preview": [
		"Use this page for inventory items, tools and weapons after their Surface or Voxel source has visible geometry.",
		"Inspect Neutral first to confirm the model itself is centred and scaled sensibly.",
		"Inspect Held to check grip position, hand clearance, orientation and whether the object blocks too much of the player's view.",
		"Inspect Dropped to confirm the item rests above the ground, is not upside down and remains recognizable from several angles.",
		"Inspect Icon at actual HUD size. Strong silhouettes and clear colour separation matter more than tiny model details here.",
		"Adjust representation transforms instead of reshaping the canonical model merely to fix one viewing context.",
		"Bake a fresh preview icon, Save Draft and Validate before testing the item in inventory and first-person gameplay.",
	],
	"Animation, Effects & Runtime States": [
		"Create and name compound parts before animation. Animation tracks target stable part keys; renaming a part later can break the clip.",
		"Use transform clips for doors, handles, gears and other rigid pieces. Put the pivot at the hinge or axle before adding rotation keys.",
		"For a continuously turning gear, animate a full rotation and use a looping clip. If it swings and snaps back, check the pivot, rotation axis, final key and loop interpolation.",
		"Use material clips for glow, heat or colour pulses that do not change the model's shape.",
		"Use voxel-frame clips only for small bounded shape changes such as magical flame frames. Every frame must use the same dimensions.",
		"Add effect sockets first, then attach flames, smoke or sparks to the correct socket so they remain centred and follow moving parts.",
		"Runtime state bindings are one-way presentation rules. Choose a gameplay field such as processing, blocked or damaged, then assign visual/audio actions without changing machine logic.",
		"Use State simulator to preview inactive, active, blocked and damaged combinations, including reduced-motion mode.",
		"Save, Validate and Bake Preview. Test the real machine in game because the simulator cannot prove inventory, fuel or processing transitions.",
	],
	"Overrides, Variants & Provenance": [
		"Use an override when a project, biome, culture or accessibility layer needs a deliberate change to an existing base presentation.",
		"Choose the stable base presentation first. Do not copy the complete asset when only one palette, material, part or state needs to differ.",
		"Add only the changed fields so future improvements to the base can still flow through.",
		"Choose the correct source layer and priority. Higher-priority layers win only when they intentionally target the same field.",
		"For variants, write deterministic conditions based on stable context rather than random frame-time values.",
		"Compare the resolved preview with the base, then inspect provenance to see exactly which layer supplied every changed field.",
		"Save and Validate conflict diagnostics before approving an override or variant set.",
	],
	"World & Machine Test Preview": [
		"This page uses the baked runtime package, not unsaved canvas data. Save and Bake Preview before expecting recent changes to appear.",
		"Resolve the stable gameplay ID and confirm the package status so you know whether the preview uses Forge or a legacy fallback.",
		"Preview one instance to inspect ground contact, facing direction, collision scale and interaction readability.",
		"Preview three or more instances to expose overlapping footprints, particle clutter and obvious repeated texture patterns.",
		"For machines, simulate the important runtime states and verify effects originate from the intended sockets.",
		"If the result is wrong, return to the editable source; do not edit generated package files because the next bake replaces them.",
		"After the test looks correct, run Validation again before Approve & Bake.",
	],
	"Validation Centre": [
		"Press Validate or Ctrl+Enter after changing authoring mode, geometry, parts, sockets, collision, footprint, animation or state bindings.",
		"Critical means the change can break compatibility or existing placement. Error means the presentation cannot safely bake. Both block approval.",
		"Click or read each diagnostic's field and suggested action, then return to the named Forge page to fix it.",
		"Warnings do not always block baking, but review them for oversized voxel volumes, unusual surface resolution, collision, materials, accessibility and migration risk.",
		"An empty Voxel Model must receive visible voxels. A missing contract part/socket must be created or deliberately remapped.",
		"Run validation again after every fix; do not assume the previous list updates itself while another page is open.",
		"When no blockers remain, inspect Live Preview and use Bake Preview before final approval.",
	],
	"Blueprint Designer Handoff": [
		"Use this page when an asset will be placed by a settlement or structure blueprint rather than only by the player.",
		"Confirm the stable presentation ID; blueprint data should reference the canonical ID rather than a generated scene path.",
		"Review the palette-role handoff so blueprint materials map to existing Forge presentations without duplicating them.",
		"Confirm the placement footprint, anchor and every allowed rotation in a representative blueprint plan.",
		"Check required interaction markers, sockets and clearance cells before construction begins.",
		"Return to Forge to make presentation changes, then rebake and retest the same blueprint placement.",
	],
	"Migration Register": [
		"Migration tracks replacement of a legacy visual with an approved Forge package while preserving the same gameplay identity.",
		"Compare the old and new presentations in equivalent lighting and placement so missing faces, scale changes or orientation errors are visible.",
		"Confirm the gameplay ID and presentation contract have not changed accidentally.",
		"Compare collision, footprint, occupied cells, rotations, sockets and state bindings. These can affect existing worlds even when the mesh looks correct.",
		"Record every intentional compatibility change and the migration or fallback behavior it requires.",
		"Keep the legacy fallback available until the new package has passed preview, in-game state testing and save/load testing.",
		"Mark migration complete only after the approved package resolves through the runtime registry for the original stable ID.",
	],
	"Recovery & History": [
		"Use Ctrl+Z and Ctrl+Y first for mistakes made during the current session. Painting batches, mode switches, face pastes, layer pastes and pattern applications are designed as undoable commands.",
		"Forge autosaves dirty work shortly after edits. A recovery notice means a recoverable copy exists; it does not automatically replace the current source.",
		"Review the candidate's asset ID, revision and time before opening it so you do not restore work from another asset.",
		"Compare the recovered model and palette in Live Preview with the current saved source.",
		"Restore only the intended candidate, then immediately Save Draft under the canonical source ID.",
		"Run Validate after restoration because an autosave may have captured a structurally incomplete step.",
		"Use the previous-source backup when a completed save—not merely an unsaved edit—needs to be rolled back.",
	],
	"Presentation Forge": [
		"Use Presentation Forge after the block, item, entity or blueprint has a stable ID. It coordinates how gameplay events become bounded visual and audio responses without owning gameplay truth.",
		"Choose a presentation profile for a reusable outcome, then connect it through a presentation binding instead of calling particles, audio or lights directly from gameplay code.",
		"Confirm every profile, binding and dependency resolves through the shared Forge Asset Index. Do not create a second presentation registry or use scene paths as identity.",
		"Keep persistent owners and loop keys stable. A keyed play, update and stop lifecycle prevents duplicate effects and orphaned audio loops.",
		"Review the selected budget, accessibility profile and fallback chain before previewing. Critical cues must remain understandable when motion, flashing or audio is reduced.",
		"Use the acceptance machine to test processing, blocked and damaged state combinations before applying the same pattern to production content.",
		"Capture the contract payload and deterministic seed whenever a runtime result needs to be reproduced. Rendered node instances are outputs, not replay data.",
		"Validate and use the Test Laboratory before publishing a new profile family. Human visual and listening approval remain separate from automated validation.",
	],
	"Spatial Roles": [
		"Use semantic roles such as socket.hand.primary, foot anchors, damage regions and audio portals instead of embedding a NodePath from one scene.",
		"Choose the canonical Set 22 role first. Add an import alias only when the alternate spelling maps to exactly one canonical role.",
		"Assign an owner-local spatial map so variants, LODs and reconstructed actors can resolve the same role on different geometry.",
		"Declare exact, mirrored and fallback mappings explicitly. A fallback should report its quality rather than pretending to be an exact result.",
		"Use runtime-contact records for transient positions such as a mining impact or footstep. Give each contact an owner, timestamp and bounded lifetime.",
		"Test left/right mirroring and missing-owner behavior. Ambiguous aliases and paths that escape their owner must fail validation.",
		"Keep gameplay collision and presentation attachment separate. Spatial roles tell presentation where to appear; they do not grant damage or interaction authority.",
		"Reconstruct the owner and repeat the lookup to prove the role survives save/load without scene-path identity.",
	],
	"Events & Profiles": [
		"Start with an event or state contract that lists the permitted payload fields, types, ranges and authority policy.",
		"Build a context packet from stable owner, material, environment, intensity and spatial-role values. Never include rendered nodes or arbitrary objects.",
		"Connect the contract to one or more profiles through a binding. Put selection rules in data so the same event can resolve consistently in replay and multiplayer.",
		"Use event contracts for one-shot facts such as an impact. Use state contracts for continuous truth such as furnace processing or ward health.",
		"Validate malformed and missing payload fields before publication. Do not silently coerce an unknown contract into a plausible effect.",
		"Record timestamp, deterministic seed, sequence ID and ownership key for traces. These values make capture, prediction and reconciliation inspectable.",
		"Confirm presentation handlers read authoritative data but cannot change gameplay inventory, damage, recipes, construction or world state.",
		"Run the same fixture twice and compare trace hashes before declaring the contract deterministic.",
	],
	"VFX Graph Authoring": [
		"Create a VFX definition, choose a reusable family and voxel form, then point it to one bounded graph source.",
		"Begin with a spawn node, add only necessary transforms or curves, and end at a declared output. Cycles are invalid unless a future schema explicitly bounds them.",
		"Set maximum spawn count, lifetime, updates and requested lights. Validation rejects missing or unsafe bounds before compilation.",
		"Use owner and lifecycle keys for loops, trails and volumes so repeated play commands update the existing instance instead of leaking another one.",
		"Provide LOD, aggregation and virtualisation behavior for dense scenes. Critical cues may degrade but must not disappear without an accessible equivalent.",
		"Compile through the shared Forge bake service and inspect the immutable runtime product. Runtime simulation must not parse the editable graph every frame.",
		"Preview several repeated instances and run the dense-scene stress scenario to confirm particles, lights and pooled objects remain bounded.",
		"Capture the command stream and seed, then replay it to verify the same structural result before requesting human visual approval.",
	],
	"Sound Event Authoring": [
		"Create a Sound Event and select licensed or explicitly placeholder Sound Sources. Every production source needs provenance and usable rights evidence.",
		"Use layers and seeded variation for controlled repetition. Do not treat the 700 to 1,100 source planning range as an automatic completion target.",
		"Set concurrency, voice, distance and loop limits. Persistent sounds require stable ownership keys and an explicit stop path.",
		"Choose a spatial-audio profile and bus intent rather than wiring an AudioStreamPlayer scene path into gameplay code.",
		"Add captions and a visual or haptic equivalent for critical cues. Validate the equivalence before a critical Sound Event can publish.",
		"Compile the source event into a managed sound plan and inspect its fallback. Unverified media must retain the active legacy fallback.",
		"Test play, update, stop, virtualisation and listener arbitration, including split-screen and late-join cases.",
		"Complete a human listening and rights review separately; a clean hash proves reproducibility, not quality or legal clearance.",
	],
	"Accessibility Preview": [
		"Select an accessibility profile and quality tier before running a scenario. Test reduced motion, reduced flash, captions and critical-cue redundancy independently.",
		"Verify status remains readable without relying on colour alone. Blocked, damaged and dangerous states need shape, motion, text, sound or another redundant channel.",
		"Reduced motion should choose a stable frame, slower bounded animation or another clear equivalent; it must not hide authoritative state.",
		"Reduced flash must clamp or replace rapid emission changes. Confirm the replacement still communicates urgency.",
		"Captions must identify the event and useful direction or ownership context without exposing internal stable IDs to players.",
		"Use the accessibility matrix in Test Laboratory to run every requested mode against every declared quality tier.",
		"Record automated results and leave manual accessibility review open until a person evaluates the actual rendered and audible experience.",
		"If one mode fails, fix the shared profile or binding so every dependent asset receives the correction.",
	],
	"Capture & Replay": [
		"Capture contracts, payloads, timestamps, seeds, owner IDs and stable spatial references. Do not capture rendered particle, mesh or audio-player instances.",
		"Name the scenario and registry generation so the evidence identifies exactly which source set produced the trace.",
		"Review the trace before replaying to catch missing ownership, unbounded values or a dependency that resolved through fallback.",
		"Replay in a clean runtime state and compare the trace hash, command order and lifecycle keys with the original capture.",
		"Use continuous-state snapshots for late join. Do not replay obsolete one-shot impacts merely because they appeared earlier in the log.",
		"For predicted events, record both predicted and authoritative sequence IDs so reconciliation can confirm, replace or cancel the presentation.",
		"Store captures as replaceable verification evidence, not as gameplay saves or approved media.",
		"A matching replay proves deterministic contracts; visual and listening acceptance still require human review.",
	],
	"Test Laboratory": [
		"Choose the smallest scenario that represents the change, then run its normal, fallback, accessibility and constrained-budget cases.",
		"Use the four development acceptance fixtures for source-to-runtime checks: Mosaic Block, Relay Block, State Machine and Tuning Tool.",
		"Run malformed-contract and missing-dependency variants to prove validation fails safely and leaves the last known-good generation active.",
		"Run each deterministic scenario twice and compare its hash. A changed hash requires an explained source or contract change.",
		"Use dense-scene stress for pooling, voice, particle, light, surface and update limits. The result must report zero unbounded allocations.",
		"Test save/reconstruction, hot reload, rollback, multiplayer authority and split listeners when the changed family participates in those systems.",
		"Export the evidence index and keep manual visual, listening, accessibility, rights and owner-review fields open until completed by people.",
		"Finish with the focused Forge probes, current aggregate regression gate and git diff hygiene check.",
	],
	"Hot Reload & Repair": [
		"Stage changed records into a candidate registry generation. Staging must not alter the currently published generation.",
		"Read the compatibility report for added, modified, removed and contract-changed IDs before publication.",
		"Classify replacements and migrations explicitly. An unclassified contract-version change must block publication.",
		"Publish only after schema, dependency, alias, cycle and domain validation succeeds for the complete candidate generation.",
		"Refresh previews and runtime consumers by stable ID after publication; never patch existing instances by a generated scene path.",
		"Use rollback to restore the previous known-good generation when a consumer or test fails after publication.",
		"Repair plans are non-destructive suggestions. Review and apply them deliberately instead of allowing validation to rewrite source automatically.",
		"After repair, rerun the affected focused probe and the full gate, then update evidence and approval state without deleting the fallback early.",
	],
}


static func steps_for_page(page_title: String) -> Array:
	for title in GUIDES:
		if page_title.begins_with(str(title)):
			return GUIDES[title]
	return []


static func page_titles() -> Array:
	return GUIDES.keys()
